# Generated by Django 5.1.7 on 2025-04-26 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing_page/banner/', verbose_name='Banner Image')),
                ('title', models.CharField(max_length=100, verbose_name='Banner Title')),
                ('description', models.TextField(verbose_name='Banner Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Banner Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Banner Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Category Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Category Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Category Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(max_length=100, verbose_name='Content Section Type')),
                ('title', models.CharField(max_length=100, verbose_name='Content Section Title')),
                ('description', models.TextField(verbose_name='Content Section Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Content Section Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Content Section Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing_page/header/', verbose_name='Header Image')),
                ('title', models.CharField(max_length=100, verbose_name='Header Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Header Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Header Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Service Title')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('image', models.ImageField(upload_to='landing_page/services/', verbose_name='Service Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Service Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Service Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Order Status')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Order Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('billing_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='home.billingdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=20, verbose_name='Payment Mode')),
                ('payment_gateway', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal')], default='stripe', max_length=20, verbose_name='Payment Gateway')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('card_number', models.CharField(max_length=20, verbose_name='Card Number')),
                ('card_expiry_month', models.CharField(max_length=2, verbose_name='Card Expiry Month')),
                ('card_expiry_year', models.CharField(max_length=4, verbose_name='Card Expiry Year')),
                ('card_cvv', models.CharField(max_length=4, verbose_name='Card CVV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing_page/product/', verbose_name='Product Image')),
                ('title', models.CharField(max_length=100, verbose_name='Product Title')),
                ('quantity', models.IntegerField(verbose_name='Product Quantity')),
                ('price', models.IntegerField(verbose_name='Product Price')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Product Updated Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Order Item Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order Item Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_product', to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cart Item Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cart Item Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cart Item Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cart Item Updated Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='home.product')),
            ],
        ),
    ]
