# Generated by Django 5.1.7 on 2025-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='payment_gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal')], default='stripe', max_length=20, verbose_name='Payment Gateway'),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=20, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
