# Generated by Django 5.1.7 on 2025-04-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_order_billing_details_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='payment_gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal'), ('cash', 'Cash')], default='cash', max_length=20, verbose_name='Payment Gateway'),
        ),
    ]
