# Generated by Django 5.1.7 on 2025-04-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_billingdetails_payment_gateway'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
