# Generated by Django 5.1.7 on 2025-04-30 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cart Item Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cart Item Price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cart Item Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cart Item Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cart Item Updated Date')),
                ('billing_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='home.billingdetails')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='home.product')),
            ],
        ),
    ]
