# Generated by Django 5.1.7 on 2025-04-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='billing_details',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='BillingDetails',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
