# Generated by Django 5.1.7 on 2025-04-30 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_cartitem_billing_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=20, verbose_name='Payment Mode')),
                ('payment_gateway', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal'), ('cash', 'Cash')], default='cash', max_length=20, verbose_name='Payment Gateway')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cart Item Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cart Item Price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cart Item Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cart Item Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cart Item Updated Date')),
                ('billing_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='home.billingdetails')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='home.product')),
            ],
        ),
    ]
