# Generated by Django 5.1.7 on 2025-04-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_billingdetails_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
