# Generated by Django 5.1.7 on 2025-05-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('payment_intent', models.CharField(max_length=255, unique=True)),
                ('charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_total', models.IntegerField()),
                ('amount_received', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('payment_status', models.CharField(max_length=50)),
                ('stripe_status', models.CharField(max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.billingdetails')),
            ],
        ),
    ]
