# Generated by Django 5.1.7 on 2025-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_billingdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
